# Generated by Django 5.0.4 on 2024-05-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_todolist_deadline_todolist_description_todolist_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['deadline', 'created']},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='done',
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(default='Ongoing', max_length=10),
        ),
    ]
