# Generated by Django 5.0.4 on 2024-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_todolist_options_remove_todolist_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='description',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
