# Generated by Django 5.0.4 on 2024-05-09 12:58

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_todolist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='done',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
