# Generated by Django 5.0.4 on 2024-05-13 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_todolist_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='done',
            new_name='done_date',
        ),
    ]
