# Generated by Django 5.0.4 on 2024-05-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_done_todolist_done_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='done_date',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
