# Generated by Django 5.0.4 on 2024-05-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_todolist_done_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='done_date',
        ),
    ]
