# Generated by Django 5.0.4 on 2024-05-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_todolist_done_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='done',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
