# Generated by Django 5.0.4 on 2024-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_todolist_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='done',
        ),
        migrations.AddField(
            model_name='todolist',
            name='selesai',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
