# Generated by Django 5.0.4 on 2024-05-13 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_todolist_done_todolist_selesai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='selesai',
        ),
    ]
