# Generated by Django 5.0.4 on 2024-05-13 13:16

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_todolist_selesai'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='selesai',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
