# Generated by Django 5.0.4 on 2024-05-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_todolist_selesai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='selesai',
        ),
        migrations.AddField(
            model_name='todolist',
            name='done',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
